### ISSUE TITLE
Better validation and error handling of user input

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/roku-cli#1]
Right now we YOLO a lot of the input into the CLI and it could `panic`. There needs to be a lot more validation around user input and notify the user accordingly. I threw away a lot of the errors with the `data, _ := Func()` method.

**Comment by leonardogcsoares** [comment]
Will try to tackle this as well! =D

**Comment by blainsmith** [comment]
Awesome! This should be simple to just pass the errors up the chain so we can return them to the CLI handler functions instead of just nil.

**Comment by arxdsilva** [comment]
vendor is empty, I'll try to help you with these errors and put the vendors properly (:

**Comment by blainsmith** [comment]
Fixed with #7
