### ISSUE TITLE
Use Flags for passing params

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/roku-cli#6]
https://github.com/urfave/cli#flags

Nicer experience when managing devices.

**Comment by leonardogcsoares** [comment]
Would like to help you with this, do I need a roku device to test? =D

**Comment by walkerrandolphsmith** [comment]
Given I have been building a [roku remote](github.com/walkerrandolphsmith/roku-remote) the past week this seems like the best Hacktoberfest thing to do. Picking up

**Comment by blainsmith** [comment]
Having a device isn't needed. This is just to manage the info stored in the ’.rokuclirc’ file.

’’’
$ roku-cli devices update --name stick-2 --password new12345
’’’

**Comment by walkerrandolphsmith** [comment]
I don't know Go. I could try to pick this up, but not sure how effective I will be. Any mentors out there want to pair on it and show me the ropes?

**Comment by leonardogcsoares** [comment]
@walkerrandolphsmith not much of a mentor but we could definetly join heads and try to tackle this together! Will take this @blainsmith  =D

**Comment by blainsmith** [comment]
Nice! If you have questions hit us up in our Slack. slack.oddnetworks.com

**Comment by leonardogcsoares** [comment]
Hey @blainsmith just submitted the PR #8 =D

**Comment by blainsmith** [comment]
Fixed with #8
